version: '3'

services:
  ros:
    build:
      context: ./
      dockerfile: ros.Dockerfile
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./ros:/home/user/ros
      - /dev/input:/dev/input
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
