controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    steering_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - left_rear_axle
      - right_rear_axle
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity

steering_controller:
  ros__parameters:
    joints:
      - left_steering_joint
      - right_steering_joint
    command_interfaces:
      - position

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: imu
    frame_id: imu
