<?xml version="1.0"?>
<robot name="car" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="cylinder_inertia" params="r h m">
    <inertial>
      <mass value="${m}" />
      <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                izz="${m*r*r/2}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="box_inertia" params="w h d m">
    <inertial>
      <mass value="${m}" />
      <inertia  ixx="${m*(h*h+d*d)/12}" ixy = "0" ixz = "0"
                iyy="${m*(w*w+d*d)/12}" iyz = "0"
                izz="${m*(w*w+h*h)/12}" />
    </inertial>
  </xacro:macro>

  <xacro:macro name="null_inertial">
    <xacro:box_inertia w="0.1" h="0.1" d="0.1" m="0.1" />
  </xacro:macro>

  <xacro:property name="car_mass" value="30.0" />
  <xacro:property name="car_length" value="0.3" />
  <xacro:property name="car_width" value="0.15" />
  <xacro:property name="car_height" value="0.1" />
 
  <xacro:property name="wheel_mass" value="1"/>
  <xacro:property name="wheel_diameter" value="0.06367"/>
  <xacro:property name="wheel_width" value="0.028"/>

  <xacro:property name="front_wheel_pos" value="0.127"/>
  <xacro:property name="rear_wheel_pos" value="-0.127"/>
  <xacro:property name="axle_width" value="0.2"/>
  <xacro:property name="steering_angle_limit" value="0.785"/> <!-- about 45 degrees -->

  <xacro:property name="left" value="1"/>
  <xacro:property name="right" value="-1"/>

  <!-- maximum effort and velocity limits in Nm and rad/s -->
  <xacro:property name="steering_effort" value="10"/>
  <xacro:property name="steering_velocity" value="100"/>
  <xacro:property name="axle_effort" value="100"/>
  <xacro:property name="axle_velocity" value="100"/>


  <material name="Green">
    <color rgba="0 1.0 0 1.0"/>
  </material>


  <!-- general wheel macro without functionality -->
  <xacro:macro name="wheel" params="lr_prefix fr_prefix lr_reflect wheel_pos child">
    <link name="${lr_prefix}_${fr_prefix}_axle_carrier">
      <!--xacro:box_inertia m="0.5" w="0.01" h="0.01" d="0.01"/-->
      <xacro:null_inertial/>
    </link>
    <gazebo reference="wheel">
      <material>Carolo/MettWheel</material>
    </gazebo>

    <joint name="${lr_prefix}_${fr_prefix}_shock" type="fixed">
      <origin xyz="${wheel_pos}  ${lr_reflect * (axle_width / 2 - wheel_width / 2)} -0.03471"/>
      <parent link="chassis"/>
      <child link="${child}"/>
      <axis xyz="0 0 0"/>
    </joint>

    <joint name="${lr_prefix}_${fr_prefix}_axle" type="continuous">
      <origin xyz="0 0 0" rpy="-1.57 0 0"/>
      <parent link="${lr_prefix}_${fr_prefix}_axle_carrier"/>
      <child link="${lr_prefix}_${fr_prefix}_wheel"/>
      <axis xyz="0 0 1"/>
      <limit effort="${axle_effort}" velocity="${axle_velocity}"/>
      <dynamics damping="0.01" friction="0.1" />
    </joint>

    <link name="${lr_prefix}_${fr_prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${wheel_diameter / 2}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_diameter / 2}" h="${wheel_width}"/>
    </link>

    <gazebo reference="${lr_prefix}_${fr_prefix}_wheel">
      <mu1>0.7</mu1>
      <mu2>0.7</mu2>
      <kd>1</kd>
      <kp>100000000</kp>
      <material>Carolo/MettWheel</material>
    </gazebo>
  </xacro:macro>


  <!-- Front Wheel Macro with steering -->
  <xacro:macro name="front_wheel" params="lr_prefix fr_prefix lr_reflect wheel_pos">
    <link name="${lr_prefix}_steering_link">
      <xacro:null_inertial/>
    </link>

    <joint name="${lr_prefix}_steering_joint" type="revolute">
      <parent link="${lr_prefix}_steering_link"/>
      <child link="${lr_prefix}_${fr_prefix}_axle_carrier"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${steering_angle_limit}" upper="${steering_angle_limit}" effort="${steering_effort}" velocity="${steering_velocity}"/>
    </joint>
    <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="${fr_prefix}"
                 lr_reflect="${lr_reflect}" wheel_pos="${wheel_pos}" child="${lr_prefix}_steering_link"/>
  </xacro:macro>


  <!-- Rear Wheel Macro with motor -->
  <xacro:macro name="rear_wheel" params="lr_prefix fr_prefix lr_reflect wheel_pos">
    <xacro:wheel lr_prefix="${lr_prefix}" fr_prefix="${fr_prefix}"
                 lr_reflect="${lr_reflect}" wheel_pos="${wheel_pos}" child="${lr_prefix}_${fr_prefix}_axle_carrier"/>

  </xacro:macro>


  <link name="base_link">  
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <material name="chassis_mat"/>
    </visual>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/Grey</material>
  </gazebo>

  <!-- Main body -->
  <link name="chassis">
    <xacro:box_inertia m="${car_mass}" w="${car_length}" h="${car_width}" d="${car_height}"/>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${car_length} ${car_width} ${car_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="${car_length} ${car_width} ${car_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="chassis">
    <material>Carolo/Mett</material>
  </gazebo>

  <joint name="base_link_to_chassis" type="fixed">
    <axis xyz="0 -1 -1" />
    <parent link="base_link"/>
    <child link="chassis"/>
  </joint>

  <link name="imu">
    <!--xacro:null_inertial/-->
  </link>
  <joint name="base_link_to_imu" type="fixed">
    <origin xyz="0.0 0.0 0.0"/>
    <parent link="base_link"/>
    <child link="imu"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <gazebo reference="imu">
    <sensor name="imu" type="imu">
      <always_on>1</always_on>
      <update_rate>30.0</update_rate>
    </sensor>
  </gazebo>


  <xacro:macro name="lidar_sensor" params="idx xyz angle fov maxRange">
    <link name="lidar_link_${idx}">
      <!--xacro:null_inertial/-->
    </link>

    <joint name="lidar_joint_${idx}" type="fixed">
      <axis xyz="0 0 -1"/>
      <origin xyz="${xyz}" rpy="0 0 ${angle}"/>
      <parent link="base_link"/>
      <child link="lidar_link_${idx}"/>
    </joint>

    <gazebo reference="lidar_link_${idx}">
      <sensor type="ray" name="lidar_sensor_${idx}">
        <pose>0 0 0 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>5</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>5</samples>
              <resolution>1</resolution>
              <min_angle>-${fov}</min_angle>
              <max_angle>${fov}</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.10</min>
            <max>${maxRange}</max>
            <resolution>0.009</resolution>
          </range>
        </ray>
        <plugin name="scan" filename="libgazebo_ros_ray_sensor.so">
          <ros>
            <remapping>~/out:=tof_${idx}</remapping>
          </ros>
          <output_type>sensor_msgs/Range</output_type>
          <frame_name>tof_${idx}</frame_name>
          <radiation_type>ultrasound</radiation_type>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>


  <xacro:macro name="camera_sensor" params="xyz pitch">
    <link name="camera_link">
    </link>

    <joint name="camera_joint" type="fixed">
      <axis xyz="0 0 -1"/>
      <origin xyz="${xyz}" rpy="0 ${pitch} 0"/>
      <parent link="base_link"/>
      <child link="camera_link"/>
    </joint>

    <gazebo reference="camera_link">
      <sensor type="camera" name="camera">
        <visualize>true</visualize>
        <update_rate>30.0</update_rate>
        <camera name="camera">
          <horizontal_fov>1.5707963267948966</horizontal_fov>
          <image>
            <width>640</width>
            <height>480</height>
            <format>B8G8R8</format>
          </image>
          <clip>
            <near>0.02</near>
            <far>300</far>
          </clip>
        </camera>
        <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
          <alwaysOn>true</alwaysOn>
          <updateRate>30.0</updateRate>
          <frameName>camera_link</frameName>
        </plugin>
      </sensor>
    </gazebo>
  </xacro:macro>

  <!-- Wheels -->
  <xacro:front_wheel lr_prefix="left" fr_prefix="front" lr_reflect="${left}" wheel_pos="${front_wheel_pos}"/>
  <xacro:front_wheel lr_prefix="right" fr_prefix="front" lr_reflect="${right}" wheel_pos="${front_wheel_pos}"/>
  <xacro:rear_wheel lr_prefix="left" fr_prefix="rear" lr_reflect="${left}" wheel_pos="${rear_wheel_pos}"/>
  <xacro:rear_wheel lr_prefix="right" fr_prefix="rear" lr_reflect="${right}" wheel_pos="${rear_wheel_pos}"/>

  <xacro:lidar_sensor idx="left" xyz="0.05 0.1 0.018" angle="1.5707963267948966" fov="0.2181662" maxRange="3.0"/> <!--left-->
  <xacro:lidar_sensor idx="right" xyz="0.05 -0.1 0.018" angle="-1.5707963267948966" fov="0.2181662" maxRange="3.0"/> <!--right-->
  <xacro:lidar_sensor idx="front" xyz="0.1 0 0.018" angle="0" fov="0.08" maxRange="4.0"/> <!--front-->
  <xacro:lidar_sensor idx="back" xyz="-0.15 0 0.018" angle="-3.14159265359" fov="0.06" maxRange="1.5"/> <!--back-->
  <xacro:camera_sensor xyz="-0.07 0 0.185" pitch="-0.1"/>

  <ros2_control name="GazeboSystem" type="system">
    <hardware>
      <plugin>gazebo_ros2_control/GazeboSystem</plugin>
    </hardware>
    <joint name="left_rear_axle">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="velocity"/>
    </joint>
    <joint name="right_rear_axle">
      <command_interface name="velocity">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
      <state_interface name="velocity"/>
    </joint>
    <joint name="left_steering_joint">
      <command_interface name="position">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
    </joint>
    <joint name="right_steering_joint">
      <command_interface name="position">
        <param name="min">-10</param>
        <param name="max">10</param>
      </command_interface>
    </joint>
    <sensor name="imu">
      <state_interface name="orientation.x"/>
      <state_interface name="orientation.y"/>
      <state_interface name="orientation.z"/>
      <state_interface name="orientation.w"/>
      <state_interface name="angular_velocity.x"/>
      <state_interface name="angular_velocity.y"/>
      <state_interface name="angular_velocity.z"/>
      <state_interface name="linear_acceleration.x"/>
      <state_interface name="linear_acceleration.y"/>
      <state_interface name="linear_acceleration.z"/>
    </sensor>
  </ros2_control>

  <gazebo>
    <plugin filename="libgazebo_ros2_control.so" name="gazebo_ros2_controll">
      <robot_param>robot_description</robot_param>
      <robot_param_node>robot_state_publisher</robot_param_node>
      <parameters>$(find gazebo_simulation)/config/controller.yaml</parameters>
    </plugin>
  </gazebo>
</robot>
